import type { Profile } from "@/types/content";

export const profile: Profile = {
  name: "최다빈",
  primaryRoles: ["데이터 분석가", "데이터 프로덕트 빌더"],
  secondaryRoles: ["공간 데이터 분석가", "비즈니스/CRM 데이터 분석가"],
  industries: ["공공데이터", "상권/부동산", "리테일", "CRM", "커머스", "스포츠", "웹 데이터 제품"],
  avoidSignals: [],
  headline:
  "분석 결과를 차트에서 끝내지 않고, 판단 기준·리스크 신호·검토 가능한 산출물로 연결하는 데이터 의사결정 아카이브를 구축합니다.",
summary: [
  "공공데이터, 상권 데이터, CRM 데이터처럼 성격이 다른 데이터를 목적에 맞는 분석 단위와 지표로 다시 정리하고, 검토자가 실제로 판단할 수 있는 기준·리스크 신호·웹 결과물로 연결하는 작업을 강점으로 삼고 있습니다.",
  "React/Next/Vite 기반 웹앱, Vercel 서버리스 API route, DuckDB SQL mart, PostgreSQL local/fallback 검증, Docker/n8n/Mailpit dry-run evidence를 프로젝트 범위에 맞게 조합해 왔습니다.",
  "프로덕션 엔지니어링 범위를 과장하기보다, 분석 결과가 실제로 확인 가능한 화면·문서·검증 스크립트로 끝까지 이어지는 흐름을 중요하게 생각합니다.",
],
  strengths: [
    "문제 정의",
    "분석 설계",
    "지표 설계와 검증",
    "도메인 해석 번역력",
    "데이터 제품화",
    "자동화 검증",
  ],
  keywords: [
    "분석 설계",
    "지표 설계",
    "문제 정의",
    "데이터 제품",
    "웹앱 구현",
    "자동화 검증",
    "결과물 전달",
  ],
  contactLinks: [
    {
      label: "GitHub",
      href: "https://github.com/dffxonnb-cyber",
      displayText: "github.com/dffxonnb-cyber",
    },
    {
      label: "Email",
      href: "mailto:dffxonnb@gmail.com",
      displayText: "dffxonnb@gmail.com",
    },
  ],
  skillGroups: [
    {
      title: "Core Stack",
      summary: "분석과 구현을 함께 묶는 기본 작업 도구입니다.",
      items: ["Python", "SQL", "TypeScript", "React", "Next.js", "Vite", "Vercel", "GitHub Pages", "GitHub Actions"],
    },
    {
      title: "Data Analysis & Statistics",
      summary: "전처리, 탐색, 통계 검정, 모델링 후보 검토에 사용하는 분석 도구입니다.",
      items: [
        "pandas",
        "NumPy",
        "Jupyter Notebook",
        "SciPy",
        "scikit-learn",
        "statsmodels",
        "scikit-posthocs",
        "RFM Analysis",
        "EDA",
        "Statistical Testing",
        "Regression",
        "Clustering",
        "Predictive Modeling",
      ],
    },
    {
      title: "Database & Pipeline",
      summary: "분석 가능한 테이블 구조, 검증 가능한 SQL layer, local/fallback 범위의 데이터 산출물을 구성합니다.",
      items: [
        "PostgreSQL",
        "DuckDB",
        "Neon fallback/historical evidence",
        "SQLAlchemy",
        "psycopg",
        "SQL Migrations",
        "SQL Models",
        "SQL Tests",
        "CSV/JSON Pipeline",
        "Data Quality Checks",
        "Static JSON Export",
      ],
    },
    {
      title: "GIS / Spatial Analysis",
      summary: "도시·공공데이터 맥락에서 지역 단위 비교와 위험/후보 우선순위를 다룹니다.",
      items: [
        "GeoPandas",
        "Shapely",
        "PyProj",
        "QGIS",
        "GeoJSON",
        "Spatial Grid Analysis",
        "Risk/Candidate Ranking",
        "PostGIS integration guide",
      ],
    },
    {
      title: "Web & App",
      summary: "분석 결과를 사용자가 탐색할 수 있는 웹앱과 대시보드 형태로 구현합니다.",
      items: ["React", "Next.js", "Vite", "TypeScript", "PWA", "Static HTML/CSS/JS"],
    },
    {
      title: "Serverless & API",
      summary: "브라우저에 키를 노출하지 않는 서버리스 경유 구조와 공공데이터 API 응답 정규화에 사용합니다.",
      items: [
        "Vercel",
        "Vercel Serverless API Routes",
        "PostgreSQL fallback path",
        "data.go.kr API",
        "Public Data API Integration",
        "API Response Normalization",
        "Server-side API Key Proxy",
      ],
    },
    {
      title: "Automation & Local Infra",
      summary: "운영 자동화가 아니라 로컬 검증과 dry-run 흐름을 재현 가능하게 만드는 데 사용합니다.",
      items: [
        "Docker Compose local validation",
        "n8n dry-run outline",
        "Mailpit local capture",
        "SMTP local test",
        "Python smtplib",
        "Dry-run Bridge",
        "One-command Smoke Test",
      ],
    },
    {
      title: "Visualization & BI",
      summary: "분석 결과의 비교, 우선순위, 설명 흐름을 시각적으로 전달합니다.",
      items: ["Tableau", "Matplotlib", "Seaborn", "Plotly", "Streamlit/pydeck prototypes"],
    },
    {
      title: "Deployment & Workflow",
      summary: "정적 사이트, PWA, 포트폴리오 페이지를 검증하고 배포하는 작업 흐름입니다.",
      items: [
        "Vercel",
        "GitHub Pages",
        "Git",
        "GitHub",
        "GitHub Actions",
        "npm",
        "ESLint",
        "TypeScript tsc",
        "Next Build",
        "Vite Build",
        "Python Smoke Tests",
      ],
    },
    {
      title: "Docs & Output",
      summary: "프로젝트의 판단 근거, 한계, 실행 방법을 리뷰 가능한 문서와 산출물로 정리합니다.",
      items: ["Markdown", "README", "Troubleshooting Docs", "ReportLab", "pypdf", "python-pptx", "openpyxl"],
    },
  ],
  aiWorkflow: {
    summary:
      "AI-assisted workflow를 활용해 아이디어 구조화, 코드 초안 작성, 디버깅, 문서화를 효율화합니다. 문제 정의, 지표 설계, 결과 해석, 최종 판단 기준은 직접 검토하며, AI는 반복 작업을 줄이고 검증 시간을 확보하기 위한 보조 도구로 사용합니다.",
    items: [
      "분석 아이디어를 정리할 때 AI를 활용",
      "코드 초안 작성 및 디버깅에 AI 활용",
      "SQL/Python 에러 원인 파악에 AI 활용",
      "README, 분석 보고서, 페이지 문구 정리에 AI 활용",
      "반복 작업을 줄이고, 검증 시간을 확보하기 위한 방식으로 활용",
    ],
    note:
      "",
  },
};
